### ISSUE TITLE
Backport Android Auto to LX models

### ISSUE THREAD

**Issue by librick** [librick/ic1101#4]
Apparently wired Android Auto isn't supported for Honda Civic LX models. On my (non-LX) headunit, it looks like support is enabled via an installed [Android APK](https://github.com/librick/ic1101/commit/4a77f3a58462bbbd13ceb05942b59af947254363#diff-bde34da5bb9666d5d8865330a7f1cab87db3bdf9f8906507e2444ef13dc42d63R14). Wired Android Auto should be supported on all models provided that the headunit hardware can support it.

**Comment by kghorvath** [comment]
The 10th gen LX uses a totally different head unit. I don't think it's touchscreen and I'm not even sure if it runs Android or not.

**Comment by librick** [comment]
Thanks. I looked up a few YouTube videos reviewing the LX and can confirm; it's not a touchscreen and it looks like the software is different. The dashboard looks identical, but the headunit looks like it's running different software altogether. Although interestingly it looks like the icons are similar to the icons in the DaSettings apk (`/res/drawable/`).

As an aside, I really should document how the dashboard connects to the headunit. On a non-LX, if I enable "Show surface updates" in the Android developer options, a small section of the dashboard flashes/updates along with the headunit display itself. So I assume that the dashboard itself is at least partially managed by Android. But it's still entirely possible that the LX headunits use a different software stack altogether.

**Comment by librick** [comment]
Closing this in the interest of scope creep. If anyone wants to work on LX models I'd welcome a PR, but I don't have access to an LX headunit. I have a root tool coming soon for non-LX models and better docs coming soon for all models.

**Comment by alexpotv** [comment]
Small detail, the LX trim in the US is known as the DX trim in the Canadian market. The Canadian market also had an LX trim, but **it has the Android-based head unit**.
